
export const ADD_TO_TODO = "ADD_TO_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const EDIT_ITEM = "EDIT_ITEM"
export const HANDLE_UPDATE = "HANDLE_UPDATE"
export const TOGGLE_COMPLETE = "TOGGLE_COMPLETE"
export const COMPLETED_TASK ="COMPLETED_TASK"
export const DELETE_COMPLETED_TASK= 'DELETE_COMPLETED_TASK'
